Basic submission and plot display now working
There was a ValueError in make_assign_df() that needs properly fixing (see below). I've bodged it, but the root problem is somewhere previous.
ValueError: 'SS_name' is both an index level and a column label, which is ambiguous.

Haven't done anything with downloading results yet.